### PR TITLE
(fix) Update default valueSet UUIDs

### PR DESCRIPTION
**Pull request by denniskigen**
## Requirements

- [x] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [ ]  My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://zeroheight.com/23a080e38/p/880723-introduction).
- [ ] My work includes tests or is validated by existing tests.

## Summary

Updates default UUIDs for valueSets in the config schema to match UUIDs that exist in the dev3 environment by default.

### CODE REVIEW

**Comment by denniskigen** [comment]
@mogoodrich this is a breaking change for you. I assume that the default UUIDs that are currently set exist in the PIH EMR, so this change would require you to set those values via config instead for your distro.

**Comment by denniskigen** [comment]
Is it intentional that `reasonForPause` and `reasonForClose`  valueSets use the same CIEL concept in the dispensing app config schema? See the descriptions for the respective properties in the config schema [here](https://github.com/openmrs/openmrs-esm-dispensing-app/blob/8bacf9aa86af909b145585fef1ee848519febd5f/src/config-schema.ts#L100) and [here](https://github.com/openmrs/openmrs-esm-dispensing-app/blob/8bacf9aa86af909b145585fef1ee848519febd5f/src/config-schema.ts#L109).

**Comment by chibongho** [comment]
Deferring to @mogoodrich , but I think this change won't break us as we explicit set the config values here:

https://github.com/PIH/openmrs-config-pihemr/blob/d02efb1c445406900cb5e87a1bc6034a69a71868/configuration/frontend/base-config.json#L47

**Review by mseaton — COMMENTED** [review]
I generally disapprove of any and all default values that refer to specific metadata, and have long felt that the refapp needs to start explicitly configuring ESMs in it's config, and not expecting all ESMs to work in it by default.  I want to break this existing (anti)pattern.  That said, if we are going to insist on defaults, they should be what Mark added I think - which are the default values provided by CIEL - not by some arbitrarily different values in the refapp.

**Comment by ibacher** [comment]
@mseaton The goal here is actually switching from what seem to be PIH-specific UUIDs to CIEL-provided UUIDs. We're not inventing new metadata for the RefApp.

**Comment by mseaton** [comment]
> The goal here is actually switching from what seem to be PIH-specific UUIDs to CIEL-provided UUIDs. We're not inventing new metadata for the RefApp.

If they are the CIEL UUIDs that makes sense to me if we need to have a default.  I was making an assumption based on the existing description of those config properties in the existing code, all of which say something like `Defaults to CIEL value set: XYZ`.  If they weren't actually defaulting to CIEL value sets, and this fixes that, that makes sense.

**Comment by mseaton** [comment]
All this said, it would be nice if we could eliminate use of UUIDs like this entirely, and switch to mappings.

**Review by mogoodrich — APPROVED** [review]
Yeah, the intent here (as noted in the property descriptions) is for these default values to point to the default values provided by CIEL.  This seems correct to me.  Likely a bug/oversight on my part that these were set to PIH-specific uuids.

@denniskigen  the reason (I believe) that "close" and "pause" point to the same concept is because while there was a request in our use case to have different reason sets (which we do in the PIH dictionary) the CIEL dictionary only had a single set.

So this LGTM!

**Comment by denniskigen** [comment]
Merging this in shortly. Thanks all.

**Pull request merged**
